language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - phpenv local 5.5
  - composer self-update
  - composer install --dev --no-interaction
  - phpenv local --unset

script:
  - exit 0
  - phpunit --coverage-clover clover.xml